name: Deploy API documents
on:
  push:
    paths-ignore:
      - "benchmarks/**"
    branches:
      - "master"
    tags:
      - "v*"

env:
  DOCS_PATH: docs
  GH_REF: https://github.com/icyleaf/halite
  GH_URL: https://icyleaf.github.io/halite

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        # fetch all tags and branches
        fetch-depth: 0
    - uses: oprypin/install-crystal@v1
    - name: Generate
      id: generate
      run: |
        chmod +x .github/scripts/generate_docs.sh
        ./.github/scripts/generate_docs.sh
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.DOCS_PATH }}


